[package]
name = "simple_storage"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
assert_macros = "2.8.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
build = "scarb fmt && scarb build"

# https://github.com/software-mansion/cairo-coverage
# https://foundry-rs.github.io/starknet-foundry/testing/coverage.html
[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[tool.voyager]
simple_storage_contract = { path = "simple_storage.cairo" }
